=== M2TNAH/xml_midterm_24/xml_midterm_riddles/OE_riddles_DTD_updated.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT myAssignment (header, poem)>
<!ELEMENT  header (fileDesc)>
<!ELEMENT fileDesc (titleStmt, publicationStmt, sourceDesc)>
<!ELEMENT titleStmt (title, author)>
<!ELEMENT publicationStmt (distributor, date, pubPlace, availability)>
<!ELEMENT availability (license)>
<!ELEMENT license (#PCDATA)>
<!ELEMENT distributor (#PCDATA)> 
<!ELEMENT date (#PCDATA)>
<!ELEMENT sourceDesc (bibl)>
<!ELEMENT bibl (edition, ref, poem_title, note+, lang, author, editor, publisher, incipit)>
<!ELEMENT edition (title)>
<!ELEMENT title (idno?)>
<!ELEMENT idno (#PCDATA)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT poem_title (#PCDATA)>
<!ELEMENT lang (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT editor (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT incipit (#PCDATA)>
<!ELEMENT poem (body)>
<!ELEMENT body (l+)>
<!ELEMENT l (#PCDATA | alliteration | seg | milestone)* >
<!ELEMENT alliteration (#PCDATA)>
<!ELEMENT seg (#PCDATA) >
<!ATTLIST date when CDATA #REQUIRED>
<!ELEMENT pubPlace (#PCDATA)>
<!ATTLIST licence target CDATA #REQUIRED>
<!ELEMENT note (#PCDATA)>
<!ELEMENT milestone (#PCDATA)>
<!ATTLIST l type CDATA #REQUIRED>
<!ATTLIST milestone unit CDATA #REQUIRED>
<!ATTLIST seg type CDATA #REQUIRED>
<!ATTLIST alliteration sound CDATA #REQUIRED>
<!ATTLIST poem_title type CDATA #IMPLIED>
<!ATTLIST poem_title subtype CDATA #IMPLIED>
<!ATTLIST idno type CDATA #REQUIRED >
<!ATTLIST note type CDATA #REQUIRED>
<!ATTLIST license type CDATA #REQUIRED>
<!ATTLIST title type CDATA #IMPLIED >
<!ATTLIST  ref type CDATA #REQUIRED >
<!ATTLIST ref target CDATA #REQUIRED >

=== M2TNAH/xml_midterm_24/xml_midterm_riddles/utd_riddles_old_english.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE myAssignment SYSTEM "OE_riddles_DTD_updated.dtd">
<myAssignment>
    <header>
        <fileDesc>
            <titleStmt>
                <title></title>
                <author></author>
            </titleStmt>
            <publicationStmt>
                <distributor></distributor>
                <date when="2024-10-30"></date>
                <pubPlace></pubPlace>
                <availability>
                    <license type="http://creativecommons.org/publicdomain/mark/1.0/">
                        This work is in the public domain.
                    </license>
                </availability>
            </publicationStmt>
            <sourceDesc>               
                <bibl>    
                    <edition>
                        <title type="book">
                            <idno type ="isbn"></idno>
                        </title>
                    </edition>
                    <ref type="ark" target="ark:/13960/t9959d18g"></ref>
                    <!--artificial title given to the poem-->
                    <poem_title type="poem" subtype="artificial"></poem_title>
                    <!--pages where poem is found in the edition-->
                    <note type="pages"></note>
                    <!--number of lines in poem-->
                    <note type="lines"></note>
                    <lang></lang>
                    <author></author>
                    <editor></editor>
                    <publisher></publisher>
                    <incipit></incipit>
                </bibl>
            </sourceDesc>
        </fileDesc>
    </header>
    <poem>
        <body>    
                <l type="verse">
                    <!-- first part of the line with tags for individual alliterating words, the type corresponds to the sound which alliterates -->
                    <alliteration sound="a"></alliteration> <!-- example: the first word alliterating in a -->
                    <alliteration sound="a"></alliteration> <!-- example: the second word alliterating in a -->
                    <!-- segments to highlight words which highlight features of the sky -->
                    <seg type="sky_lexical_field"></seg>
                    <!-- caesura to respect the traditional (editorial) presentation of Old English poetry -->
                    <milestone unit="caesura"/>
                    <!-- same structure as above after the caesura -->
                    <alliteration sound="b"></alliteration> <!-- example: the first word alliterating in b -->
                    <alliteration sound="b"></alliteration> <!-- example: the second word alliterating in b -->
                    <seg type="sky_lexical_field"></seg>
                </l>
                <l type="verse">
                    <alliteration sound="a"></alliteration> 
                    <alliteration sound="a"></alliteration> 
                    <seg type="sky_lexical_field"></seg>
                    <milestone unit="caesura"/>
                    <alliteration sound="b"></alliteration> 
                    <alliteration sound="b"></alliteration> 
                    <seg type="sky_lexical_field"></seg>
                </l>
                <l type="verse">
                    <alliteration sound="a"></alliteration> 
                    <alliteration sound="a"></alliteration> 
                    <seg type="sky_lexical_field"></seg>
                    <milestone unit="caesura"/>
                    <alliteration sound="b"></alliteration>
                    <alliteration sound="b"></alliteration> 
                    <seg type="sky_lexical_field"></seg>
                </l>
        </body>
    </poem>
</myAssignment>
